name: region_of_interest
description: Capture precise regions on live camera views effortlessly. Streamline image dataset capture on mobile devices with ease using region_of_interest Flutter package.
version: 0.0.1
homepage: https://github.com/jawad111/region_of_interest

# This package supports all platforms listed below.
platforms:
  android:
  ios:

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+7
  image: ^4.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  http: ^1.1.0

